substitutions:
  _REGION: asia-east1
  _SERVICE: backend
  _AR_REPO: cloud-run-source-deploy

steps:
  - id: Buildpack
    name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - build
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA
      - --builder=gcr.io/buildpacks/builder:latest
      - --network=cloudbuild
      - --publish
      - --path=backend

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA
      - --region=${_REGION}
      - --allow-unauthenticated
      - --quiet

options:
  # Required when the trigger runs as a user-specified service account
  logging: CLOUD_LOGGING_ONLY
